const Koa = require('koa')
const InitManager = require('./core/init')
const parser = require('koa-bodyparser')
const app = new Koa()
const catchError = require('./middlewares/exception')
app.use(catchError)
app.use(parser())
InitManager.initCore(app)
app.listen(3000)
 